version: "3.8"

services:
  item-app:
    image: "ghcr.io/fallinnadim/item-app:v1"
    ports:
      - 80:8080
    volumes:
      - ./:/app
    depends_on:
      - item-db
    restart: always
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    restart: always

volumes:
  app-db: